In [46]:
import glob
import pandas as pd
import datetime

# get data file names
path =r'sp500/csv'
# ！！！CAUTION: need minutes to process all files！！！
filenames = glob.glob(path + "/*.csv")

# date_time_obj = datetime.datetime.strptime(date_time_str, '%d-%m-%Y')

# print('Date:', date_time_obj.date())

startDate = datetime.datetime.strptime('01-01-2005', '%d-%m-%Y')
endDate = datetime.datetime.strptime('01-01-2021', '%d-%m-%Y')

df_empty = pd.DataFrame(columns=[])
for filename in filenames:
    stockName = filename.split('/')[2].split('.csv')[0]
    print(stockName)
    
    df_tmp = pd.read_csv(filename)
    date_time_obj = datetime.datetime.strptime(df_tmp.iloc[0, 0], '%d-%m-%Y')
    print(date_time_obj)
    if startDate < date_time_obj:
        print("skip")
    else :
#         dummy algo, find the first row that date >= startDate
        i = 0
        while i < len(df_tmp.index) and datetime.datetime.strptime(df_tmp.iloc[i, 0], '%d-%m-%Y') < startDate:
            i += 1
#         concatenate df_tmp[i:] to df_empty
        if i < len(df_tmp.index):
#             print(i)
            df_tmp_open_filtered = df_tmp.iloc[i:]
            df_tmp_open_filtered = df_tmp_open_filtered.reset_index()
#             df_tmp_filtered.index = Series(range(1, len(df_tmp_filtered))   
            df_empty[stockName + ' Date'] = df_tmp_open_filtered['Date']
            df_empty[stockName + ' Open'] = df_tmp_open_filtered['Open']
            df_empty[stockName + ' Close'] = df_tmp_open_filtered['Close']
            df_empty[stockName + ' Low'] = df_tmp_open_filtered['Low']
            df_empty[stockName + ' High'] = df_tmp_open_filtered['High']
            df_empty[stockName + ' Volume'] = df_tmp_open_filtered['Volume']
            df_empty[stockName + ' Adjusted Close'] = df_tmp_open_filtered['Adjusted Close']
                                           
#             df_empty[filename] = df_tmp['Open'].iloc[i:]
#             df_empty[filename + ' Date'] = df_tmp['Date'].iloc[i:]

CSCO
1990-02-16 00:00:00
UAL
2006-02-06 00:00:00
skip
TROW
1986-04-02 00:00:00
ISRG
2000-06-16 00:00:00
NVR
1985-07-22 00:00:00
CHMD
2016-07-12 00:00:00
skip
MRO
1970-01-02 00:00:00
BA
1970-01-02 00:00:00
GILD
1992-01-22 00:00:00
NLSN
2011-01-27 00:00:00
skip
EQIX
2000-08-11 00:00:00
MDT
1973-05-02 00:00:00
V
2008-03-19 00:00:00
skip
QRVO
2015-01-02 00:00:00
skip
A
1999-11-18 00:00:00
FLT
2010-12-15 00:00:00
skip
MO
1970-01-02 00:00:00
SWKS
1984-09-07 00:00:00
MCHP
1993-03-19 00:00:00
CDNS
1987-06-10 00:00:00
MSCI
2007-11-15 00:00:00
skip
CHTR
2010-01-05 00:00:00
skip
EIX
1973-05-03 00:00:00
GS-PJ
2013-04-22 00:00:00
skip
BBY
1985-04-18 00:00:00
WBA
1980-03-17 00:00:00
LVS
2004-12-15 00:00:00
HCA
2011-03-10 00:00:00
skip
AJG
1984-06-20 00:00:00
DTE
1970-01-02 00:00:00
C
1977-01-03 00:00:00
T
1983-11-21 00:00:00
CF
2005-08-11 00:00:00
skip
FPLPF
2012-06-18 00:00:00
skip
MGM
1988-05-02 00:00:00
HUM
1981-12-31 00:00:00
CFG
2014-09-24 00:00:00
skip
WU
2006-10-02 00:00:00
skip
APH
1991-11-08 00:00:00
MSI
1977-01-03 00:00:00
FCX
1995-07-10 00:00:00
ADM
1980-03-17 00:00:00
LH
1990-03-29 00:00:00
GGG
1980-03-17 00:00:00
ALTR
2017-11-01 00:00:00
skip
PKI
1973-02-21 00:00:00
LNT
1973-02-21 00:00:00
BAC
1973-02-21 00:00:00
LNC
1980-03-17 00:00:00
PSX
2012-04-12 00:00:00
skip
GPN
2001-01-16 00:00:00
PPG
1980-03-17 00:00:00
KGNR
2015-06-09 00:00:00
skip
IRM
1996-02-01 00:00:00
ESS
1994-06-07 00:00:00
NOV
1996-10-29 00:00:00
HAL
1972-06-01 00:00:00
FLS
1980-03-17 00:00:00
ADI
1980-03-17 00:00:00
F
1972-06-01 00:00:00
CPRT
1994-03-17 00:00:00
ULTA
2007-10-25 00:00:00
skip
ARE
1997-05-28 00:00:00
SYK
1980-03-17 00:00:00
CB
1993-03-25 00:00:00
TSN
1980-03-17 00:00:00
PEP
1972-06-01 00:00:00
PEG
1980-01-02 00:00:00
NOXL
2012-06-18 00:00:00
skip
NOW
2012-06-29 00:00:00
skip
COST
1986-07-09 00:00:00
REG
1993-10-29 00:00:00
LOW
1980-03-17 00:00:00
MDLZ
2001-06-13 00:00:00
FMC
1980-03-17 00:00:00
XEL
1973-02-21 00:00:00
AIZ
2004-02-05 00:00:00
UEEC
2021-01-05 00:00:00
skip
MET
2000-04-05 00:00:00
ATURF
2010-12-31 00:00:00
skip
FAST
1987-08-20 00:00:00
TJX
1987-06-26 00:00:00
MPC
2011-06-24 00:00:00
skip
BR
2007-04-02 00:00:00
skip
D
1980-03-17 00:00:00
MRK
1970-01-02 00:00:00
STX
2002-12-11 00:00:00
NOC
1981-12-31 00:00:00
BXP
1997-06-18 00:00:00
KHC
2015-07-06 00:00:00
skip
UNP
1980-01-02 00:00:00
ALLE
2013-11-18 00:00:00
skip
ABBV
2013-01-02 00:00:00
skip
ECL
1973-02-21 00:00:00
EBAY
1998-09-24 00:00:00
SBUX
1992-06-26 00:00:00
IR
2017-05-12 00:00:00
skip
AMT
1998-02-27 00:00:00
INTU
1993-03-12 00:00:00
DPZ
2004-07-13 00:00:00
DRE
1986-02-06 00:00:00
IPGP
2006-12-13 00:00:00
skip
PG
1970-01-02 00:00:00
CAT
1970-01-02 00:00:00
ODFL
1991-10-24 00:00:00
MCD
1970-01-02 00:00:00
MNST
1985-12-09 00:00:00
AMZN
1997-05-15 00:00:00
WSPOF
2013-02-27 00:00:00
skip
PNR
1973-05-03 00:00:00
BDX
1973-02-21 00:00:00
COWN
2006-07-13 00:00:00
skip
PWR
1998-02-12 00:00:00
DXCM
2005-04-14 00:00:00
skip
EXR
2004-08-16 00:00:00
HOLX
1990-03-01 00:00:00
GM
2010-11-18 00:00:00
skip
TXN
1972-06-01 00:00:00
VRSK
2009-10-07 00:00:00
skip
TMO
1980-03-17 00:00:00
OXY
1981-12-31 00:00:00
RL
1997-06-12 00:00:00
GLUU
2007-03-22 00:00:00
skip
TCYSF
2013-02-28 00:00:00
skip
CCI
1998-08-18 00:00:00
MMM
1970-01-02 00:00:00
MOS
1988-01-26 00:00:00
HSY
1980-03-17 00:00:00
JNPR
1999-06-25 00:00:00
DHI
1992-06-05 00:00:00
ED
1970-01-02 00:00:00
ES
1973-02-21 00:00:00
ADSK
1985-06-28 00:00:00
IP
1970-01-02 00:00:00
KO
1970-01-02 00:00:00
PCAR
1980-03-17 00:00:00
WDC
1978-10-31 00:00:00
NEE
1973-02-21 00:00:00
UPS
1999-11-10 00:00:00
FLIR
1993-06-22 00:00:00
LEG
1980-03-17 00:00:00
EMR
1972-06-01 00:00:00
MSFT
1986-03-13 00:00:00
CTAS
1983-08-19 00:00:00
BIO
1980-02-27 00:00:00
NCTKF
2012-01-17 00:00:00
skip
UDR
1980-03-17 00:00:00
WEC
1980-03-17 00:00:00
NVRO
2014-11-06 00:00:00
skip
AME
1984-07-19 00:00:00
IT
1993-10-05 00:00:00
ACN
2001-07-19 00:00:00
VRSN
1998-01-30 00:00:00
EW
2000-03-27 00:00:00
CMG
2006-01-26 00:00:00
skip
AWK
2008-04-23 00:00:00
skip
COO
1983-01-21 00:00:00
SHW
1980-03-17 00:00:00
HPQ
1970-01-02 00:00:00
RIBT
2003-10-01 00:00:00
AMAT
1980-03-17 00:00:00
MLM
1994-02-17 00:00:00
AVY
1973-02-21 00:00:00
AAP
2001-11-29 00:00:00
ATVI
1993-10-25 00:00:00
EA
1989-09-20 00:00:00
DE
1972-06-01 00:00:00
SPG
1993-12-14 00:00:00
AMD
1980-03-17 00:00:00
NDAQ
2002-07-01 00:00:00
URI
1997-12-18 00:00:00
WHR
1973-02-21 00:00:00
KMX
1997-02-04 00:00:00
WRK
2015-06-24 00:00:00
skip
RLI
1980-03-17 00:00:00
XLEFF
2012-06-18 00:00:00
skip
IFGNF
2010-09-22 00:00:00
skip
BIIB
1991-09-17 00:00:00
CHRW
1997-10-16 00:00:00
ROP
1992-02-13 00:00:00
RXMD
2010-03-09 00:00:00
skip
IDXX
1991-06-21 00:00:00
HES
1980-03-17 00:00:00
HD
1981-09-22 00:00:00
ALB
1994-02-22 00:00:00
CTQ
2011-06-08 00:00:00
skip
AON
1980-06-02 00:00:00
ZTS
2013-02-01 00:00:00
skip
FDX
1978-04-12 00:00:00
DG
2009-11-13 00:00:00
skip
TYL
1980-03-17 00:00:00
CAG
1980-03-17 00:00:00
SCHW
1987-09-22 00:00:00
HSIC
1995-11-03 00:00:00
AZO
1991-04-02 00:00:00
AXP
1972-06-01 00:00:00
HPE
2015-10-19 00:00:00
skip
DFS
2007-06-14 00:00:00
skip
SEE
1980-03-17 00:00:00
HRL
1980-03-17 00:00:00
SO
1981-12-31 00:00:00
FRT
1973-05-03 00:00:00
ZBH
2001-07-25 00:00:00
FRC
2010-12-09 00:00:00
skip
CME
2002-12-06 00:00:00
FN
2010-06-25 00:00:00
skip
XOM
1970-01-02 00:00:00
AMP
2005-09-15 00:00:00
skip
PNW
1973-02-21 00:00:00
ICE
2005-11-16 00:00:00
skip
CTXS
1995-12-08 00:00:00
BEN
1983-09-23 00:00:00
VNO-PK
2012-07-23 00:00:00
skip
UHS
1981-07-09 00:00:00
BHI
2018-08-28 00:00:00
skip
EMN
1993-12-14 00:00:00
ROK
1981-12-31 00:00:00
SEGXF
2007-09-25 00:00:00
skip
NRG
2003-12-02 00:00:00
NSC
1982-06-02 00:00:00
NMHLY
2015-09-25 00:00:00
skip
KACPF
2013-04-09 00:00:00
skip
FIS
2001-06-20 00:00:00
FANG
2012-10-12 00:00:00
skip
VTR
1997-05-05 00:00:00
RF
1980-03-17 00:00:00
TAP
1975-06-12 00:00:00
MAR
1993-10-13 00:00:00
BMRA
1984-09-07 00:00:00
XYL
2011-10-13 00:00:00
skip
CMI
1973-02-21 00:00:00
FB
2012-05-18 00:00:00
skip
VAR
1980-03-17 00:00:00
KR
1977-01-03 00:00:00
PLD
1997-11-21 00:00:00
IBM
1970-01-02 00:00:00
USB
1973-05-03 00:00:00
BSX
1992-05-19 00:00:00
LKQ
2003-10-06 00:00:00
FBHS
2011-09-16 00:00:00
skip
ITW
1973-03-13 00:00:00
FRMC
2016-12-16 00:00:00
skip
TWTR
2013-11-07 00:00:00
skip
EOG
1989-10-04 00:00:00
PVH
1980-03-17 00:00:00
KMB
1980-03-17 00:00:00
NTRA
2015-07-01 00:00:00
skip
INTH
2013-02-15 00:00:00
skip
EL
1995-11-17 00:00:00
GD
1977-01-03 00:00:00
CNP
1970-01-02 00:00:00
PM
2008-03-17 00:00:00
skip
RE
1995-10-03 00:00:00
MCO
1994-10-31 00:00:00
CLX
1973-02-21 00:00:00
CAH
1983-08-04 00:00:00
HRB
1973-02-21 00:00:00
HTLF
1999-01-04 00:00:00
DGX
1996-12-17 00:00:00
AVB
1994-03-11 00:00:00
DIS
1970-01-02 00:00:00
GE
1970-01-02 00:00:00
HII
2011-03-22 00:00:00
skip
LDOS
2006-10-17 00:00:00
skip
BF-A
1973-05-03 00:00:00
ALGN
2001-01-30 00:00:00
NFLX
2002-05-23 00:00:00
FITB
1980-03-17 00:00:00
WST
1980-03-17 00:00:00
ORBC
2006-11-06 00:00:00
skip
GWW
1973-02-21 00:00:00
ENS
2004-08-02 00:00:00
NTRS
1980-03-17 00:00:00
MS-PF
2013-12-09 00:00:00
skip
SRG
2015-07-06 00:00:00
skip
AOS
1983-09-30 00:00:00
FE
1997-11-10 00:00:00
ABC
1995-04-04 00:00:00
JPM
1980-03-17 00:00:00
ABT
1980-03-17 00:00:00
OMC
1980-03-17 00:00:00
TSCO
1994-02-17 00:00:00
PH
1980-03-17 00:00:00
HST
1980-03-17 00:00:00
JBHT
1983-11-22 00:00:00
COP
1981-12-31 00:00:00
COG
1990-02-08 00:00:00
CNC
2001-12-13 00:00:00
MCK
1994-11-10 00:00:00
TXT
1973-02-21 00:00:00
HFC
1980-03-17 00:00:00
NTRR
2011-10-12 00:00:00
skip
AKAM
1999-10-29 00:00:00
ROL
1980-03-17 00:00:00
RMD
1995-06-02 00:00:00
WRB
1973-10-23 00:00:00
ANET
2014-06-06 00:00:00
skip
RSNHF
2014-05-29 00:00:00
skip
TRAUF
2006-07-05 00:00:00
skip
PAYX
1983-08-26 00:00:00
ALK
1980-03-17 00:00:00
DRI
1995-05-09 00:00:00
CUK
2000-10-23 00:00:00
ILMN
2000-07-28 00:00:00
AAL
2005-09-27 00:00:00
skip
MRCR
2000-08-16 00:00:00
XLNX
1990-06-12 00:00:00
MAA
1994-01-28 00:00:00
FMBM
1999-03-16 00:00:00
MMC
1973-02-21 00:00:00
STZ-B
2002-07-17 00:00:00
FFIV
1999-06-04 00:00:00
CINF
1980-03-17 00:00:00
VMC
1973-02-21 00:00:00
MKTX
2004-11-05 00:00:00
SRE
1998-06-29 00:00:00
ORLY
1993-04-23 00:00:00
IVZ
1995-08-25 00:00:00
RCL
1993-04-28 00:00:00
PXD
1997-08-08 00:00:00
COTY
2013-06-13 00:00:00
skip
SNPS
1992-02-26 00:00:00
GOOG
2004-08-19 00:00:00
SIVB
1987-10-26 00:00:00

YUM
1997-09-17 00:00:00
LYV
2005-12-21 00:00:00
skip
KSS
1992-05-19 00:00:00
PFE
1972-06-01 00:00:00
REGN
1991-04-02 00:00:00
CL
1973-05-02 00:00:00
VFC
1980-03-17 00:00:00
BSHI
1999-06-10 00:00:00
UA
2016-03-23 00:00:00
skip
VZ
1983-11-21 00:00:00
JCI
1987-09-28 00:00:00
CDE
1980-03-17 00:00:00
AMGN
1983-06-17 00:00:00
TEL
2007-06-14 00:00:00
skip
JKHY
1985-11-20 00:00:00
ADP
1980-03-17 00:00:00
SONC
2012-06-18 00:00:00
skip
LB
1982-04-01 00:00:00
STT
1980-03-17 00:00:00
KRA
2009-12-17 00:00:00
skip
RSG
1998-07-01 00:00:00
IFF
1974-12-17 00:00:00
ANTM
2001-10-30 00:00:00
LYB
2010-04-28 00:00:00
skip
GIS
1980-03-17 00:00:00
PHM
1980-03-17 00:00:00
ROST
1985-08-08 00:00:00
LBTYA
2004-06-03 00:00:00
LUV
1980-01-02 00:00:00
ALXN
1996-02-28 00:00:00
CPB
1973-02-21 00:00:00
OKE
1980-10-01 00:00:00
BK
1973-05-03 00:00:00
SYF
2014-07-31 00:00:00
skip
CHD
1980-03-17 00:00:00
SLG
1997-08-15 00:00:00
MHK
1992-04-01 00:00:00
DAL
2007-05-03 00:00:00
skip
APA
1979-05-15 00:00:00
K
1973-02-21 00:00:00
NI
1973-02-21 00:00:00
NCLH
2013-01-18 00:00:00
skip
ZION
1980-03-17 00:00:00
CPICQ
1982-07-30 00:00:00
PNWRF
2012-08-03 00:00:00
skip
RJF
1983-07-01 00:00:00
HBAN
1980-03-17 00:00:00
PRU
2001-12-13 00:00:00
GPC
1980-03-17 00:00:00
FISV
1986-09-25 00:00:00
WMB
1981-12-31 00:00:00
EQR
1993-08-12 00:00:00
MXIM
1988-02-29 00:00:00
PBCT
1988-07-06 00:00:00
KSU
1980-03-17 00:00:00
DVA
1995-10-31 00:00:00
HBI
2006-09-06 00:00:00
skip
HON
1970-01-02 00:00:00
O
1994-10-18 00:00:00
BRK-A
1980-03-17 00:00:00
TTWO
1997-04-15 00:00:00
CNWT
1999-11-05 00:00:00
SLB
1981-12-31 00:00:00
AAPL
1980-12-12 00:00:00
FCGN
2012-12-04 00:00:00
skip
WY
1973-05-03 00:00:00
APD
1980-03-17 00:00:00
GRMN
2000-12-08 00:00:00
AEE
1998-01-02 00:00:00
HLT
2013-12-12 00:00:00
skip
NEOG
1989-08-23 00:00:00
DLTR
1995-03-07 00:00:00
HAS
1980-03-17 00:00:00
TMUS
2007-04-19 00:00:00
skip
NTAP
1995-11-21 00:00:00
KIM
1991-11-22 00:00:00
BAX
1981-10-27 00:00:00
LMT
1977-01-03 00:00:00
ABMD
1987-07-29 00:00:00
KEY
1987-11-05 00:00:00
UNM
1986-11-06 00:00:00
KEYS
2014-10-20 00:00:00
skip
BMY
1972-06-01 00:00:00
WYNN
2002-10-25 00:00:00
RHI
1980-03-17 00:00:00
EFX
1980-03-17 00:00:00
PKG
2000-01-28 00:00:00
NOK
1994-01-03 00:00:00
CTSH
1998-06-19 00:00:00
SWK
1980-03-17 00:00:00
MU
1984-06-01 00:00:00
TRV
1975-11-17 00:00:00
AEP
1970-01-02 00:00:00
TW
2019-04-04 00:00:00
skip
JNJ
1970-01-02 00:00:00
WM
1988-06-22 00:00:00
DOV
1980-03-17 00:00:00
FTI
2001-06-15 00:00:00
CRM
2004-06-23 00:00:00
WAT
1995-11-17 00:00:00
IEX
1989-06-02 00:00:00
BWA
1993-08-13 00:00:00
LRCX
1984-05-04 00:00:00
NWL
1980-03-17 00:00:00
BLK
1999-10-01 00:00:00

In [47]:
df_empty

,CSCO Date,CSCO Open,CSCO Close,CSCO Low,CSCO High,CSCO Volume,CSCO Adjusted Close,TROW Date,TROW Open,TROW Close,...,NWL High,NWL Volume,NWL Adjusted Close,BLK Date,BLK Open,BLK Close,BLK Low,BLK High,BLK Volume,BLK Adjusted Close
0,03-01-2005,19.420000,19.320000,19.270000,19.610001,56725600,14.448113,03-01-2005,31.230000,30.830000,...,24.549999,1706900,14.724539,03-01-2005,77.010002,75.779999,75.769997,77.349998,25900,52.010536
1,04-01-2005,19.379999,18.559999,18.540001,19.389999,106241900,13.879755,04-01-2005,30.844999,29.969999,...,24.129999,1234800,14.491594,04-01-2005,75.769997,75.550003,74.949997,76.250000,24500,51.852680
2,05-01-2005,18.469999,18.570000,18.450001,18.879999,66100500,13.887231,05-01-2005,29.905001,29.844999,...,23.510000,1095500,14.191222,05-01-2005,75.699997,74.849998,74.750000,75.699997,24600,51.372242
3,06-01-2005,18.670000,18.850000,18.559999,18.860001,63790900,14.096630,06-01-2005,29.785000,30.129999,...,23.299999,1257800,14.228000,06-01-2005,76.250000,80.000000,76.209999,80.580002,300600,54.906906
4,07-01-2005,18.920000,18.719999,18.620001,18.980000,54415000,13.999409,07-01-2005,30.180000,29.905001,...,23.400000,1079400,14.240260,07-01-2005,80.000000,78.339996,77.949997,81.000000,147300,53.767574
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4077,16-03-2021,49.189999,49.669998,49.189999,49.740002,17126900,49.669998,16-03-2021,174.000000,172.160004,...,26.120001,2777600,25.680000,16-03-2021,721.940002,723.070007,715.760010,727.390015,554700,723.070007
4078,17-03-2021,49.610001,49.419998,48.889999,49.610001,18096000,49.419998,17-03-2021,171.509995,174.720001,...,26.049999,2069800,25.879999,17-03-2021,721.349976,728.219971,719.909973,730.400024,457600,728.219971
4079,18-03-2021,48.520000,48.799999,48.520000,49.570000,18416900,48.799999,18-03-2021,175.490005,171.869995,...,26.680000,2819600,26.290001,18-03-2021,728.989990,723.729980,722.460022,739.950012,640100,723.729980
4080,19-03-2021,48.709999,48.980000,48.320000,49.220001,65364000,48.980000,19-03-2021,171.669998,171.850006,...,26.510000,5495100,26.090000,19-03-2021,720.260010,729.640015,713.510010,740.650024,1437100,729.640015
4081,22-03-2021,48.939999,50.076401,48.939999,50.330002,16337983,50.076401,22-03-2021,172.026001,172.550003,...,26.250000,1137220,26.115000,22-03-2021,729.640015,731.590027,725.570007,736.190002,321450,731.590027

In [44]:
pd.DataFrame(df_empty.iloc[0:100])

,sp500/csv/CSCO.csv Date,sp500/csv/CSCO.csv Open,sp500/csv/CSCO.csv Close,sp500/csv/CSCO.csv Low,sp500/csv/CSCO.csv High,sp500/csv/CSCO.csv Volume,sp500/csv/CSCO.csv Adjusted Close,sp500/csv/TROW.csv Date,sp500/csv/TROW.csv Open,sp500/csv/TROW.csv Close,...,sp500/csv/NWL.csv High,sp500/csv/NWL.csv Volume,sp500/csv/NWL.csv Adjusted Close,sp500/csv/BLK.csv Date,sp500/csv/BLK.csv Open,sp500/csv/BLK.csv Close,sp500/csv/BLK.csv Low,sp500/csv/BLK.csv High,sp500/csv/BLK.csv Volume,sp500/csv/BLK.csv Adjusted Close
0,03-01-2005,19.420000,19.320000,19.270000,19.610001,56725600,14.448113,03-01-2005,31.230000,30.830000,...,24.549999,1706900,14.724539,03-01-2005,77.010002,75.779999,75.769997,77.349998,25900,52.010536
1,04-01-2005,19.379999,18.559999,18.540001,19.389999,106241900,13.879755,04-01-2005,30.844999,29.969999,...,24.129999,1234800,14.491594,04-01-2005,75.769997,75.550003,74.949997,76.250000,24500,51.852680
2,05-01-2005,18.469999,18.570000,18.450001,18.879999,66100500,13.887231,05-01-2005,29.905001,29.844999,...,23.510000,1095500,14.191222,05-01-2005,75.699997,74.849998,74.750000,75.699997,24600,51.372242
3,06-01-2005,18.670000,18.850000,18.559999,18.860001,63790900,14.096630,06-01-2005,29.785000,30.129999,...,23.299999,1257800,14.228000,06-01-2005,76.250000,80.000000,76.209999,80.580002,300600,54.906906
4,07-01-2005,18.920000,18.719999,18.620001,18.980000,54415000,13.999409,07-01-2005,30.180000,29.905001,...,23.400000,1079400,14.240260,07-01-2005,80.000000,78.339996,77.949997,81.000000,147300,53.767574
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,19-05-2005,19.230000,19.379999,19.180000,19.430000,46846000,14.492977,19-05-2005,29.590000,29.745001,...,22.629999,731700,13.957426,19-05-2005,78.339996,78.239998,77.669998,78.839996,42000,53.901134
96,20-05-2005,19.389999,19.469999,19.280001,19.510000,34181700,14.560287,20-05-2005,29.790001,29.764999,...,22.730000,755100,14.037855,20-05-2005,78.360001,78.209999,77.550003,78.400002,49300,53.880459
97,23-05-2005,19.350000,19.549999,19.330000,19.590000,49768500,14.620111,23-05-2005,29.820000,29.860001,...,23.020000,1566600,14.167782,23-05-2005,78.250000,78.050003,78.000000,78.849998,55200,53.770252
98,24-05-2005,19.480000,20.000000,19.400000,20.010000,86130000,14.956637,24-05-2005,29.860001,29.639999,...,23.000000,2240600,14.118283,24-05-2005,78.000000,77.500000,76.650002,78.050003,92400,53.391335
99,25-05-2005,19.840000,19.620001,19.510000,19.889999,66102100,14.672464,25-05-2005,29.504999,29.165001,...,22.620001,1561300,13.980907,25-05-2005,77.500000,77.580002,77.099998,77.839996,63500,53.446468