In [8]:
import glob
import pandas as pd

# get data file names
path =r'totalCSV'
filenames = glob.glob(path + "/*.csv")

df_empty = pd.DataFrame(columns=[])
for filename in filenames:
    df_empty[filename] = pd.read_csv(filename)['Open']
df_empty

,totalCSV/CSCO.csv,totalCSV/CSBK.csv,totalCSV/SBGI.csv,totalCSV/UFCS.csv,totalCSV/GFED.csv,totalCSV/AIRT.csv,totalCSV/NXN.csv,totalCSV/BNY.csv,totalCSV/ISSC.csv,totalCSV/KNDI.csv,...,totalCSV/BLK.csv,totalCSV/BMO.csv,totalCSV/NXC.csv,totalCSV/SPXX.csv,totalCSV/NVCN.csv,totalCSV/OBCI.csv,totalCSV/ANTH.csv,totalCSV/ARDC.csv,totalCSV/MTDR.csv,totalCSV/BWEN.csv
0,0.000000,10.11,11.75,0.000000,4.142931,2.916667,15.0,15.00,7.083333,3.90,...,14.000,9.2500,15.000,20.0,250.0,1.402334,448.000000,19.750000,11.75,35.500000
1,0.000000,10.13,11.75,2.034568,4.272398,2.916667,15.0,15.00,8.020833,3.70,...,14.125,9.2500,15.000,20.0,250.0,1.402334,451.200012,19.950001,12.00,32.700001
2,0.000000,10.07,11.75,2.034568,4.401865,2.916667,15.0,15.05,8.062500,3.80,...,14.000,9.3125,15.000,20.0,250.0,1.308845,457.600006,20.000000,11.97,31.000000
3,0.000000,10.22,11.75,2.034568,4.790264,2.916667,15.0,15.01,8.020833,3.75,...,14.125,9.3125,15.000,20.0,250.0,1.215356,458.880005,20.010000,11.94,35.000000
4,0.000000,10.16,11.75,2.034568,4.919731,2.916667,15.0,15.00,8.062500,3.75,...,14.875,9.1250,15.125,20.0,220.0,1.215356,448.640015,20.000000,12.00,35.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7828,49.189999,NaN,NaN,19.180000,NaN,13.133333,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.270000,NaN,NaN,NaN,NaN
7829,49.610001,NaN,NaN,19.120001,NaN,12.986667,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.220000,NaN,NaN,NaN,NaN
7830,48.520000,NaN,NaN,19.469999,NaN,12.853333,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.310000,NaN,NaN,NaN,NaN
7831,48.709999,NaN,NaN,19.719999,NaN,13.460000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.260000,NaN,NaN,NaN,NaN
7832,48.939999,NaN,NaN,20.350000,NaN,13.600000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.350000,NaN,NaN,NaN,NaN